#!/usr/bin/env ruby
# frozen_string_literal: true

require 'gtk4'
require 'fileutils'

# Require all ruby files in the application folder recursively
# alternative for __dir__ is "."
application_root_path = File.expand_path(__dir__)
Dir.glob(File.join(application_root_path, '**', '*.rb'), &method(:require))

# Define the source & target files of the glib-compile-resources command
resource_xml = File.join(application_root_path, 'resources', 'gresources.xml')
resource_bin = File.join(application_root_path, 'gresource.bin')

# Build the binary
system('glib-compile-resources',
       '--target', resource_bin,
       '--sourcedir', File.dirname(resource_xml),
       resource_xml)

resource = Gio::Resource.load(resource_bin)
Gio::Resources.register(resource)

at_exit do
  FileUtils.rm_f(resource_bin)
end

app = Homebank::Application.new
app.run
