name: Linting
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@ec02537da5712d66d4d50a0f33b7eb52773b5ed1
        with:
          ruby-version: '2.6'
      - name: Install rubocop
        run: gem install rubocop -v 1.50.2
      - name: Get content of dic
        run: ls -l
      - name: Rubocop
        run: rubocop