name: Linting
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@ec02537da5712d66d4d50a0f33b7eb52773b5ed1
        with:
          ruby-version: '3.2.2' # Not needed with a .ruby-version file
      - name: Install rubocop
        run: gem install rubocop -v 1.58.0
      - name: Rubocop
        run: rubocop